name: Practice CI with Day Time Check Project | 2021 by Little Kid

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Build with Ant
        run: ant -noinput -buildfile build.xml
    
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Run the Ant jar target
        run: ant -noinput -buildfile build-ci.xml jar
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
      - run: ant -noinput -buildfile build.xml
      - uses: actions/upload-artifact@v2
        with:
          name: 1.0-SNAPSHOT.jar
          path: staging/jar
          
